import type { Ytelse } from '@/lib/kodeverk';

export const ytelserSimple: Ytelse[] = [
  { id: '41', navn: 'AA-register' },
  { id: '25', navn: 'Alderspensjon' },
  { id: '9', navn: 'Arbeidsavklaringspenger (AAP)' },
  { id: '27', navn: 'Avtalefestet pensjon (AFP)' },
  { id: '26', navn: 'Barnepensjon' },
  { id: '10', navn: 'Barnetrygd' },
  { id: '11', navn: 'Bidragsområdet - Barnebidrag' },
  { id: '46', navn: 'Bidragsområdet - Barnebortføring' },
  { id: '12', navn: 'Bidragsområdet - Bidragsforskudd' },
  { id: '15', navn: 'Bidragsområdet - Bidragsinnkreving' },
  { id: '14', navn: 'Bidragsområdet - Ektefellebidrag' },
  { id: '45', navn: 'Bidragsområdet - Far- og morskap' },
  { id: '13', navn: 'Bidragsområdet - Oppfostringsbidrag' },
  { id: '16', navn: 'Dagpenger' },
  { id: '17', navn: 'Enslig mor eller far' },
  { id: '7', navn: 'Foreldrepenger - Engangsstønad' },
  { id: '6', navn: 'Foreldrepenger - Foreldrepenger' },
  { id: '8', navn: 'Foreldrepenger - Svangerskapspenger' },
  { id: '51', navn: 'Forsikring' },
  { id: '48', navn: 'Forskudd dagpenger' },
  { id: '30', navn: 'Gjenlevende - Gjenlevende' },
  { id: '52', navn: 'Gjenlevende - Omstillingsstønad' },
  { id: '19', navn: 'Gravferdsstønad' },
  { id: '21', navn: 'Grunn- og hjelpestønad - Grunnstønad' },
  { id: '20', navn: 'Grunn- og hjelpestønad - Hjelpestønad' },
  { id: '49', navn: 'Hjelpemidler - Bil og motorkjøretøy' },
  { id: '50', navn: 'Hjelpemidler - Ortopediske' },
  { id: '22', navn: 'Hjelpemidler - Tekniske' },
  { id: '43', navn: 'Kompensasjonsytelse for selvstendig næringsdrivende og frilansere' },
  { id: '23', navn: 'Kontantstøtte' },
  { id: '29', navn: 'Krigspensjon' },
  { id: '18', navn: 'Lønnsgaranti' },
  { id: '47', navn: 'Lønnskompensasjon for permitterte' },
  { id: '24', navn: 'Medlemskap' },
  { id: '40', navn: 'Oppfølgingssak - NAV-loven §14a' },
  { id: '34', navn: 'Oppfølgingssak - Tiltaksplass' },
  { id: '42', navn: 'Støtte til arbeids- og utdanningsreiser' },
  { id: '31', navn: 'Supplerende stønad' },
  { id: '32', navn: 'Supplerende stønad til uføre flyktninger' },
  { id: '1', navn: 'Sykdom i familien - Omsorgspenger' },
  { id: '2', navn: 'Sykdom i familien - Opplæringspenger' },
  { id: '4', navn: 'Sykdom i familien - Pleiepenger i livets sluttfase' },
  { id: '3', navn: 'Sykdom i familien - Pleiepenger sykt barn' },
  { id: '5', navn: 'Sykepenger' },
  { id: '44', navn: 'Tilleggsstønad' },
  { id: '33', navn: 'Tiltakspenger' },
  { id: '39', navn: 'Tvungen forvalting' },
  { id: '35', navn: 'Uføretrygd' },
  { id: '37', navn: 'Yrkesskade - Menerstatning' },
  { id: '36', navn: 'Yrkesskade - Yrkesskade' },
  { id: '38', navn: 'Yrkesskade - Yrkessykdom' },
];
