apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: mine-klager
  namespace: klage
  labels:
    team: klage
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
spec:
  port: 3000
  image: {{ image }}
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  prometheus:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: kabal-api
        - application: klage-kodeverk-api
        - application: nav-dekoratoren
          namespace: personbruker
  ingresses:
  - {{ingress}}
  envFrom:
    - secret: slack-url
  observability:
    tracing:
      enabled: true
